[package]
name = "wwcombo"
version = "0.65.2"
default-run = "wwcombo"
description = "Wuthering Waves combo trainer"
authors = ["NovaWallace"]
license = "MIT"
edition = "2021"

[lib]
name = "wwcombo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = []
release-core = []

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
once_cell = "1"
parking_lot = "0.12"
base64 = "0.22"
flate2 = "1"
sha2 = "0.10"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = ["Gaming_Input", "Win32_System_WinRT"] }
hidapi = "2.6.3"

[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.15"
